repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
        name: check newlines
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: golangci-lint
        name: golangci-lint
      - id: go-mod-tidy
        name: go mod tidy
  - repo: local
    hooks:
      - id: make-api
        name: make api
        entry: make api
        language: system
        pass_filenames: false
