linters:
  enable:
    - gofmt
    - goimports
    - exhaustruct

linters-settings:
  exhaustruct:
    exclude:
      - "net/http.Server"
      - "github.com/sashabaranov/go-openai.ChatCompletionRequest"
      - "github.com/sashabaranov/go-openai.ChatCompletionMessage"
      - "github.com/sashabaranov/go-openai.ImageRequest"
