openapi: 3.0.0

info:
  version: 1.0.0
  title: FetchmojiAI Service
  description: A Slack bot service that generates emojis

servers:
  - url: http://localhost:8080/v1

paths:
  /imagine:
    post:
      description: Imagines an emoji
      operationId: imagine
      tags:
        - Imagine
      requestBody:
        description: The request body to imagine an emoji
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                prompt:
                  description: A prompt to imagine
                  type: string
              required:
                - prompt
      responses:
        200:
          $ref: "#/components/responses/ImagineResponse"
        400:
          $ref: "#/components/responses/BadRequest"
        500:
          $ref: "#/components/responses/InternalServerError"

components:
  schemas:
    Error:
      description: A generic error
      properties:
        status:
          type: integer
          format: int64
          example: 500
        code:
          $ref: '#/components/schemas/ErrorCode'
          example: ERROR
        message:
          type: string
          example: Error
      required:
        - status
        - code
        - message

    ErrorCode:
      type: string
      enum:
        - ERROR

  responses:
    ImagineResponse:
      description: Imagine Response
      content:
        application/json:
          schema:
            properties:
              image:
                description: A URL to the imagination
                type: string
            required:
              - image
  
    BadRequest:
        description: Bad Request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'

    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
